# Generated by Django 6.0.3 on 2026-03-21 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('housing', 'Housing'), ('utilities', 'Utilities'), ('shopping', 'Shopping'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('savings', 'Savings'), ('other', 'Other'), ('investments', 'Investments')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.category'),
        ),
    ]
