# Generated by Django 6.0.3 on 2026-03-29 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_category_name_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 29, 13, 41, 53, 379589, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
