# Generated by Django 6.0.3 on 2026-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_transaction_date_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_investment',
            field=models.BooleanField(default=False),
        ),
    ]
